name: Cache
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
uses: actions/cache@v3.0.8
with:
  path:
    - 'code'
  key: ${{ runner.os }}-target-libraries
  # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
  restore-keys: # optional

