name: Cache builds.
on:
  pull_request:
    branches: ["main", "development", "alpha", "production", "published"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3

      - name: Cache
        id: cache-target
        uses: actions/cache@v3.0.8
